version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
        - "5432:5432"
  web:
    container_name: wikidegreesapp
    build: 
        context: .
        dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db